"""add completed column in season table

Revision ID: 0d83cd5935f0
Revises: bc0a7e8add19
Create Date: 2025-12-04 16:27:53.398473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d83cd5935f0'
down_revision = 'bc0a7e8add19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_360p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_480p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_720p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_1080p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_qualities', sa.JSON(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_360p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_480p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_720p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_1080p', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_qualities', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('video_qualities')
        batch_op.drop_column('video_1080p')
        batch_op.drop_column('video_720p')
        batch_op.drop_column('video_480p')
        batch_op.drop_column('video_360p')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('video_qualities')
        batch_op.drop_column('video_1080p')
        batch_op.drop_column('video_720p')
        batch_op.drop_column('video_480p')
        batch_op.drop_column('video_360p')

    # ### end Alembic commands ###
