"""Add bytescale fields

Revision ID: 152a7b4b36b1
Revises: c571406b8e66
Create Date: 2025-12-08 19:30:52.007495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152a7b4b36b1'
down_revision = 'c571406b8e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_servers', schema=None) as batch_op:
        batch_op.alter_column('server_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('base_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_servers', schema=None) as batch_op:
        batch_op.alter_column('base_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('server_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
