"""Added dub download link column

Revision ID: 2ea138952338
Revises: 4332d888f85a
Create Date: 2026-01-15 12:01:32.859649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea138952338'
down_revision = '4332d888f85a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dub_download_link', sa.String(length=200), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dub_download_link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('dub_download_link')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('dub_download_link')

    # ### end Alembic commands ###
