"""add completed column in season table

Revision ID: 4033f1556f77
Revises: 96197427b479
Create Date: 2025-12-02 00:48:40.696358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4033f1556f77'
down_revision = '96197427b479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
