"""Added coming soon boolean

Revision ID: 4332d888f85a
Revises: 5be30221a34d
Create Date: 2026-01-12 08:10:42.494785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4332d888f85a'
down_revision = '5be30221a34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coming_soon', sa.Boolean(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coming_soon', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('coming_soon')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('coming_soon')

    # ### end Alembic commands ###
