"""Add Season table

Revision ID: 594c306a8fb7
Revises: bbadf977df05
Create Date: 2025-12-12 12:07:30.743463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c306a8fb7'
down_revision = 'bbadf977df05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('trailer_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('length_per_episode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('season', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length_per_episode', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('trailer_url')
        batch_op.drop_column('image')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
