"""Add search logs and active user tracking

Revision ID: 5be30221a34d
Revises: c446679ba326
Create Date: 2026-01-05 19:23:50.098333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be30221a34d'
down_revision = 'c446679ba326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 👇 COMMENTED OUT because 'search_term' already exists on Neon
    # op.create_table('search_term',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('term', sa.String(length=100), nullable=False),
    # sa.Column('count', sa.Integer(), nullable=True),
    # sa.Column('last_searched', sa.DateTime(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )

    # 👇 THESE STAY ACTIVE (To add the missing columns)
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('views')

    # op.drop_table('search_term')
    # ### end Alembic commands ###