"""Add index to RecentItem.date_added

Revision ID: 68f3d0831223
Revises: 81c20c414375
Create Date: 2025-11-25 15:21:13.587259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f3d0831223'
down_revision = '81c20c414375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_item_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_item_episode_id'), ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_item_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_item_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_item_video_id'))
        batch_op.drop_index(batch_op.f('ix_recent_item_type'))
        batch_op.drop_index(batch_op.f('ix_recent_item_episode_id'))
        batch_op.drop_index(batch_op.f('ix_recent_item_date_added'))

    op.drop_table('recent_item')
    # ### end Alembic commands ###
