"""add completed column in season table

Revision ID: 6e53418cc954
Revises: 0d83cd5935f0
Create Date: 2025-12-04 17:04:13.788489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e53418cc954'
down_revision = '0d83cd5935f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_360p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_480p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_720p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_1080p', sa.String(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_360p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_480p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_720p', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thumb_1080p', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('thumb_1080p')
        batch_op.drop_column('thumb_720p')
        batch_op.drop_column('thumb_480p')
        batch_op.drop_column('thumb_360p')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('thumb_1080p')
        batch_op.drop_column('thumb_720p')
        batch_op.drop_column('thumb_480p')
        batch_op.drop_column('thumb_360p')

    # ### end Alembic commands ###
