"""Add index to RecentItem.date_added

Revision ID: 7154b5d3c2a6
Revises: 
Create Date: 2025-11-25 13:04:34.349017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7154b5d3c2a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_item_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_item_type'))

    # ### end Alembic commands ###
