"""Add index to RecentItem.date_added

Revision ID: 81c20c414375
Revises: 7154b5d3c2a6
Create Date: 2025-11-25 14:33:34.642050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c20c414375'
down_revision = '7154b5d3c2a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_recentitem_series',  # <- give it a name
            'series',                # target table
            ['series_id'],           # local column
            ['id']                   # remote column
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recentitem_series', type_='foreignkey')
        batch_op.drop_column('series_id')

    # ### end Alembic commands ###
