"""Added CourseLead table

Revision ID: 8dc4ee555fff
Revises: 7b9d2c1e4f20
Create Date: 2026-06-14 20:49:15.401698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc4ee555fff'
down_revision = '7b9d2c1e4f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('course_interest', sa.String(length=150), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_lead', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_lead_date_added'), ['date_added'], unique=False)

    op.drop_table('alembic_version')
    with op.batch_alter_table('sports_sport', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sports_sport_slug_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_sports_sport_slug'))
        batch_op.create_index(batch_op.f('ix_sports_sport_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sports_sport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sports_sport_slug'))
        batch_op.create_index(batch_op.f('ix_sports_sport_slug'), ['slug'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('sports_sport_slug_key'), ['slug'], postgresql_nulls_not_distinct=False)

    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    with op.batch_alter_table('course_lead', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_lead_date_added'))

    op.drop_table('course_lead')
    # ### end Alembic commands ###
