"""newer

Revision ID: b5c38cb9dd75
Revises: b6c91679763a
Create Date: 2025-12-07 18:42:47.634862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c38cb9dd75'
down_revision = 'b6c91679763a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_all_video_slug', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_constraint('uq_all_video_slug', type_='unique')
        batch_op.drop_column('slug')
    # ### end Alembic commands ###
