"""add email history table

Revision ID: b70603f1f8d5
Revises: 8dc4ee555fff
Create Date: 2026-07-05 19:23:32.457780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70603f1f8d5'
down_revision = '8dc4ee555fff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.String(length=120), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_history_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_history_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_history_to_email'), ['to_email'], unique=False)

    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    with op.batch_alter_table('email_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_history_to_email'))
        batch_op.drop_index(batch_op.f('ix_email_history_status'))
        batch_op.drop_index(batch_op.f('ix_email_history_sent_at'))

    op.drop_table('email_history')
    # ### end Alembic commands ###
