"""Allow nullable video_id and trailer_id

Revision ID: bbadf977df05
Revises: efdc1ece1327
Create Date: 2025-12-11 13:58:54.421764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbadf977df05'
down_revision = 'efdc1ece1327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recent_item_episode_id'))
        batch_op.drop_index(batch_op.f('ix_recent_item_video_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recent_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recent_item_video_id'), ['video_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recent_item_episode_id'), ['episode_id'], unique=False)

    # ### end Alembic commands ###
