"""Allow nullable video_id and trailer_id

Revision ID: bc0a7e8add19
Revises: 4033f1556f77
Create Date: 2025-12-03 00:49:34.687927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc0a7e8add19'
down_revision = '4033f1556f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_comment', sa.Integer(), nullable=True))

    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_comment', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trailer', schema=None) as batch_op:
        batch_op.drop_column('total_comment')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('total_comment')

    # ### end Alembic commands ###
