"""Syncing DB

Revision ID: c446679ba326
Revises: 
Create Date: 2026-01-05 17:10:11.390832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c446679ba326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        # 👇 I added a # here to SKIP this line because Neon already has it
        # batch_op.add_column(sa.Column('backup_link', sa.String(length=500), nullable=True))
        
        # 👇 This line stays active (to add the downloads column)
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        # 👇 I added a # here to SKIP this too (just to be safe)
        # batch_op.add_column(sa.Column('backup_link', sa.String(length=500), nullable=True))
        
        # 👇 This line stays active
        batch_op.add_column(sa.Column('downloads', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('downloads')
        # batch_op.drop_column('backup_link')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('downloads')
        # batch_op.drop_column('backup_link')

    # ### end Alembic commands ###