"""add backup link

Revision ID: ea1808952ca9
Revises: 
Create Date: 2026-01-03 11:02:00.107209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1808952ca9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_link', sa.String(length=500), nullable=True))

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('backup_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('backup_link')

    with op.batch_alter_table('all_video', schema=None) as batch_op:
        batch_op.drop_column('backup_link')

    # ### end Alembic commands ###
