"""add pool and notify tables

Revision ID: f6ad08006f74
Revises: 190700991f79
Create Date: 2026-03-13 12:39:03.550090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ad08006f74'
down_revision = '190700991f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_poll', schema='public') as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_poll_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_poll_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_poll_is_active'), ['is_active'], unique=False)

    op.create_table('weekly_poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=180), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['weekly_poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_poll_option', schema='public') as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_poll_option_poll_id'), ['poll_id'], unique=False)

    op.create_table('watchlist_notify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telegram', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['all_video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_notify', schema='public') as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_notify_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_notify_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_notify_telegram'), ['telegram'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_notify_video_id'), ['video_id'], unique=False)

    op.create_table('weekly_poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('voter_token', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['weekly_poll_option.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poll_id'], ['weekly_poll.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_poll_vote', schema='public') as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_poll_vote_date_added'), ['date_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_poll_vote_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_poll_vote_poll_id'), ['poll_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_poll_vote_voter_token'), ['voter_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_poll_vote', schema='public') as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_poll_vote_voter_token'))
        batch_op.drop_index(batch_op.f('ix_weekly_poll_vote_poll_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_poll_vote_option_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_poll_vote_date_added'))

    op.drop_table('weekly_poll_vote')
    with op.batch_alter_table('watchlist_notify', schema='public') as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_notify_video_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_notify_telegram'))
        batch_op.drop_index(batch_op.f('ix_watchlist_notify_email'))
        batch_op.drop_index(batch_op.f('ix_watchlist_notify_date_added'))

    op.drop_table('watchlist_notify')
    with op.batch_alter_table('weekly_poll_option', schema='public') as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_poll_option_poll_id'))

    op.drop_table('weekly_poll_option')
    with op.batch_alter_table('weekly_poll', schema='public') as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_poll_is_active'))
        batch_op.drop_index(batch_op.f('ix_weekly_poll_ends_at'))
        batch_op.drop_index(batch_op.f('ix_weekly_poll_date_added'))

    op.drop_table('weekly_poll')
    # ### end Alembic commands ###
